volumes:
  postgres-data:

services:
  db:
    container_name: db
    image: postgis/postgis
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - "5432:5432"


networks:
  app_network:
    driver: bridge