spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  secrets:
    secretKey: ${SECRET_KEY:defaultSecretKey}
  gemini:
    secretKey: ${GEMINI_KEY:defaultSecretKey}

---
spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      enabled: true
      start:
        command: up
      stop:
        command: stop
        timeout: 10s

---
spring:
  config:
    activate:
      on-profile: aws
  docker:
    compose:
      enabled: false

---
#kakao local API KEY
api-key:
  url: ${KAKAO_LOCAL_URL}
  key: ${KAKAO_LOCAL_KEY}

---
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---
spring:
  data:
    redis:
      host: ${REDIS_HOST}   # Redis 서버 주소 (localhost 또는 외부 서버)
      port: ${REDIS_PORT}   # Redis 포트 (기본적으로 6379)
      password: ${REDIS_PASSWORD}  # Redis 서버 비밀번호 (requirepass 설정에 맞춰야 함)
      username: ${REDIS_USERNAME}