package com.sparta.deliveryapp.menu.dto;

public class MenuSwaggerExample {

  public static final String MENU_LIST_EXAMPLE = "{\n"
      + "    \"content\": [\n"
      + "        {\n"
      + "            \"menu_uuid\": \"da26ef6a-97ca-4df3-8912-5d8a4e662b63\",\n"
      + "            \"store_uuid\": \"3a21fa78-a72a-4b4d-9413-e61fa0c914ca\",\n"
      + "            \"menu_name\": \"test3\",\n"
      + "            \"menu_info\": \"맛있어요\",\n"
      + "            \"price\": 10000,\n"
      + "            \"image\": null\n"
      + "        },\n"
      + "        {\n"
      + "            \"menu_uuid\": \"7343bdb1-6ad2-4769-bb09-515e323f10fe\",\n"
      + "            \"store_uuid\": \"3a21fa78-a72a-4b4d-9413-e61fa0c914ca\",\n"
      + "            \"menu_name\": \"test2\",\n"
      + "            \"menu_info\": \"맛있어요\",\n"
      + "            \"price\": 10000,\n"
      + "            \"image\": null\n"
      + "        },\n"
      + "        {\n"
      + "            \"menu_uuid\": \"66a71e70-7509-402e-9fee-09d019c0c700\",\n"
      + "            \"store_uuid\": \"3a21fa78-a72a-4b4d-9413-e61fa0c914ca\",\n"
      + "            \"menu_name\": \"test1\",\n"
      + "            \"menu_info\": \"맛있어요\",\n"
      + "            \"price\": 10000,\n"
      + "            \"image\": null\n"
      + "        }\n"
      + "    ],\n"
      + "    \"pageable\": {\n"
      + "        \"pageNumber\": 0,\n"
      + "        \"pageSize\": 10,\n"
      + "        \"sort\": {\n"
      + "            \"empty\": false,\n"
      + "            \"sorted\": true,\n"
      + "            \"unsorted\": false\n"
      + "        },\n"
      + "        \"offset\": 0,\n"
      + "        \"paged\": true,\n"
      + "        \"unpaged\": false\n"
      + "    },\n"
      + "    \"last\": true,\n"
      + "    \"totalPages\": 1,\n"
      + "    \"totalElements\": 3,\n"
      + "    \"size\": 10,\n"
      + "    \"number\": 0,\n"
      + "    \"sort\": {\n"
      + "        \"empty\": false,\n"
      + "        \"sorted\": true,\n"
      + "        \"unsorted\": false\n"
      + "    },\n"
      + "    \"first\": true,\n"
      + "    \"numberOfElements\": 3,\n"
      + "    \"empty\": false\n"
      + "}\n";
}
