package com.sparta.deliveryapp.review.dto;


public class ReviewSwaggerExample {

  public static final String STORE_REVIEW_LIST_EXAMPLE = "{\n"
      + "    \"content\": [\n"
      + "        {\n"
      + "            \"menu_uuid\": \"da26ef6a-97ca-4df3-8912-5d8a4e662b63\",\n"
      + "            \"store_uuid\": \"3a21fa78-a72a-4b4d-9413-e61fa0c914ca\",\n"
      + "            \"menu_name\": \"test3\",\n"
      + "            \"menu_info\": \"맛있어요\",\n"
      + "            \"price\": 10000,\n"
      + "            \"image\": null\n"
      + "        },\n"
      + "        {\n"
      + "            \"menu_uuid\": \"7343bdb1-6ad2-4769-bb09-515e323f10fe\",\n"
      + "            \"store_uuid\": \"3a21fa78-a72a-4b4d-9413-e61fa0c914ca\",\n"
      + "            \"menu_name\": \"test2\",\n"
      + "            \"menu_info\": \"맛있어요\",\n"
      + "            \"price\": 10000,\n"
      + "            \"image\": null\n"
      + "        },\n"
      + "        {\n"
      + "            \"menu_uuid\": \"66a71e70-7509-402e-9fee-09d019c0c700\",\n"
      + "            \"store_uuid\": \"3a21fa78-a72a-4b4d-9413-e61fa0c914ca\",\n"
      + "            \"menu_name\": \"test1\",\n"
      + "            \"menu_info\": \"맛있어요\",\n"
      + "            \"price\": 10000,\n"
      + "            \"image\": null\n"
      + "        }\n"
      + "    ],\n"
      + "    \"pageable\": {\n"
      + "        \"pageNumber\": 0,\n"
      + "        \"pageSize\": 10,\n"
      + "        \"sort\": {\n"
      + "            \"empty\": false,\n"
      + "            \"sorted\": true,\n"
      + "            \"unsorted\": false\n"
      + "        },\n"
      + "        \"offset\": 0,\n"
      + "        \"paged\": true,\n"
      + "        \"unpaged\": false\n"
      + "    },\n"
      + "    \"last\": true,\n"
      + "    \"totalPages\": 1,\n"
      + "    \"totalElements\": 3,\n"
      + "    \"size\": 10,\n"
      + "    \"number\": 0,\n"
      + "    \"sort\": {\n"
      + "        \"empty\": false,\n"
      + "        \"sorted\": true,\n"
      + "        \"unsorted\": false\n"
      + "    },\n"
      + "    \"first\": true,\n"
      + "    \"numberOfElements\": 3,\n"
      + "    \"empty\": false\n"
      + "}\n";

  public static final String USER_REVIEW_LIST_EXAMPLE = "{\n"
      + "  \"content\": [\n"
      + "    {\n"
      + "      \"review_uuid\": \"09cc727a-78a9-4126-b517-22d9456f47d6\",\n"
      + "      \"comment\": \"맛있어요\",\n"
      + "      \"store_uuid\": \"3a21fa78-a72a-4b4d-9413-e61fa0c914ca\",\n"
      + "      \"image\": \"string\",\n"
      + "      \"rating\": 2\n"
      + "    },\n"
      + "    {\n"
      + "      \"review_uuid\": \"ba0388ca-be1a-4c20-85bc-7abed395f557\",\n"
      + "      \"comment\": \"맛있어요\",\n"
      + "      \"store_uuid\": \"3a21fa78-a72a-4b4d-9413-e61fa0c914ca\",\n"
      + "      \"image\": \"string\",\n"
      + "      \"rating\": 3\n"
      + "    },\n"
      + "    {\n"
      + "      \"review_uuid\": \"fe59c195-fd6a-4763-998c-85d9c77d5567\",\n"
      + "      \"comment\": \"맛있어요\",\n"
      + "      \"store_uuid\": \"3a21fa78-a72a-4b4d-9413-e61fa0c914ca\",\n"
      + "      \"image\": \"string\",\n"
      + "      \"rating\": 3\n"
      + "    },\n"
      + "    {\n"
      + "      \"review_uuid\": \"83aab310-2637-4486-b4a7-fa1b6c00c2e3\",\n"
      + "      \"comment\": \"맛있어요\",\n"
      + "      \"store_uuid\": \"3a21fa78-a72a-4b4d-9413-e61fa0c914ca\",\n"
      + "      \"image\": \"string\",\n"
      + "      \"rating\": 3\n"
      + "    }\n"
      + "  ],\n"
      + "  \"pageable\": {\n"
      + "    \"pageNumber\": 0,\n"
      + "    \"pageSize\": 10,\n"
      + "    \"sort\": {\n"
      + "      \"empty\": false,\n"
      + "      \"unsorted\": false,\n"
      + "      \"sorted\": true\n"
      + "    },\n"
      + "    \"offset\": 0,\n"
      + "    \"unpaged\": false,\n"
      + "    \"paged\": true\n"
      + "  },\n"
      + "  \"last\": true,\n"
      + "  \"totalPages\": 1,\n"
      + "  \"totalElements\": 4,\n"
      + "  \"first\": true,\n"
      + "  \"size\": 10,\n"
      + "  \"number\": 0,\n"
      + "  \"sort\": {\n"
      + "    \"empty\": false,\n"
      + "    \"unsorted\": false,\n"
      + "    \"sorted\": true\n"
      + "  },\n"
      + "  \"numberOfElements\": 4,\n"
      + "  \"empty\": false\n"
      + "}";
}
