name: githubaction

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    environment: cicd

    services:
      mysql:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - "5432:5432"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew clean build
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          KAKAO_LOCAL_KEY: ${{ secrets.KAKAO_LOCAL_KEY }}
          KAKAO_LOCAL_URL: ${{ secrets.KAKAO_LOCAL_URL }}
          GEMENI_KEY: ${{ secrets.GEMENI_KEY }}

      - name: make zip
        run: zip -qq -r app.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp app.zip s3://delivery-9zo/cicd/app.zip

      - name: Aws Code Deploy
        run: aws deploy create-deployment --application-name delivery9zo
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name deliveryGroup
          --s3-location bucket=delivery-9zo,bundleType=zip,key=app.zip
